"""SQLite database helpers"""

import sqlite3
from typing import Any, cast

from flask import g


def get_connection() -> sqlite3.Connection:
    """Return a configured SQLite connection"""
    con = sqlite3.connect("database.db")
    con.execute("PRAGMA foreign_keys = ON")
    con.row_factory = sqlite3.Row
    return con


def execute(sql: str, params: list[Any] | None = None) -> None:
    """Execute a SQL statement and commit it"""
    if params is None:
        params = []

    con = get_connection()
    result = con.execute(sql, params)
    con.commit()
    g.last_insert_id = result.lastrowid
    con.close()


def last_insert_id() -> int | None:
    """Return the ID generated by the most recent INSERT"""
    return cast(int | None, g.last_insert_id)


def query(
    sql: str,
    params: list[Any] | None = None,
) -> list[sqlite3.Row]:
    """Execute a SQL query and return all selected rows"""
    if params is None:
        params = []

    con = get_connection()
    result = con.execute(sql, params).fetchall()
    con.close()
    return result
